CALL InsertTree(
    1, -- Tree ID
    'Encino', -- Common Name
    'Quercus', -- Scientific Name
    '5', -- Trunk Diameter (pulgadas)
    6, -- Canopy Width (m)
    6, -- Height (m)
    10, -- Age (years)
    'Buenas', -- Tree Condition
    NULL -- Notes
);
CALL InsertTree( 2, 'Canelo', 'Drimys','12', 10, 9, 5, 'Buenas', NULL); 
CALL InsertTree(3, 'Anacahuita', 'Cordia boissieri','8', 6, 6, 4, 'Buenas', NULL);
CALL InsertTree(4, 'Anacua', 'Ehretia anacua','6', 6, 8, 6, 'Buenas', NULL);
CALL InsertTree(5, 'Encino Rojo', 'Quercus texana','5', 8, 7, 9, 'Buenas', NULL);
CALL InsertTree(6, 'Encino Roble', 'Quercus polymorpha','4', 7, 6, 8, 'Buenas', NULL);
CALL InsertTree(7, 'Encino', 'Quercus','4', 4, 6, 8, 'Buenas', NULL);
CALL InsertTree(8, 'Encino', 'Quercus','5', 6, 5, 8, 'Buenas', NULL);
CALL InsertTree(9, 'Encino', 'Quercus','6', 5, 4, 8, 'Buenas', NULL);
CALL InsertTree(10, 'Encino', 'Quercus','8', 4, 3, 8, 'Buenas', NULL);
CALL InsertTree(11, 'Encino', 'Quercus','5', 4, 4, 21, 'Buenas', NULL);
CALL InsertTree(12, 'Encino', 'Quercus','6', 6, 5, 25, 'Buenas', NULL);
CALL InsertTree(13, 'Encino', 'Quercus','4', 3, 3.5, 18, 'Buenas', NULL);
CALL InsertTree(14, 'Tepehuaje', 'Lysiloma acapulquense','9', 8, 7, 34, 'Buenas', NULL);
CALL InsertTree(15, 'Aacahuita', 'Blepharocalyx salicifolius','5', 3, 3, 19, 'Buenas', NULL);
CALL InsertTree(16, 'Aacahuita', 'Blepharocalyx salicifolius','3', 3, 2, 14, 'Buenas', NULL);
CALL InsertTree(17, 'Pino', 'Pinus sylvestris','13', 4, 9, 42, 'Buenas', NULL);
CALL InsertTree(18, 'Anacua', 'Ehretia anacua','2-3', 3, 3, 15, 'Buenas', NULL);
CALL InsertTree(19, 'Retama', 'Retama sphaerocarpa','8', 4, 4, 27, 'Buenas', NULL);
CALL InsertTree(20, 'Naranjillo', 'Citronella mucronata ','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(21, 'Hierba del Potro', 'Caesalpina mexicana','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(22, 'Retama', 'Retama sphaerocarpa','10', 10, 7, 37, 'Buenas', 'Lindero');
CALL InsertTree(23, 'Mezquite', 'Prosopis laevigata','6', 6, 5, 25, 'Buenas', NULL);
CALL InsertTree(24, 'Potro', 'Equus ferus caballus','2', 2, 3, 13, 'Buenas', NULL);
CALL InsertTree(25, 'Anacua', 'Ehretia anacua','5', 6, 3, 21, 'Buenas', NULL);
CALL InsertTree(26, 'Anacua', 'Ehretia anacua','6', 4, 4, 23, 'Buenas', NULL);
CALL InsertTree(27, 'Potro', 'Equus ferus caballus','2', 3, 3, 13, 'Buenas', NULL);
CALL InsertTree(28, 'Potro', 'Equus ferus caballus','4', 4, 3, 18, 'Buenas', NULL);
CALL InsertTree(29, 'Encino', 'Quercus','6', 4, 4, 23, 'Buenas', NULL);
CALL InsertTree(30, 'Aacahuita', 'Blepharocalyx salicifolius','3', 3, 2, 14, 'Buenas', NULL);
CALL InsertTree(31, 'Encino Rojo', 'Quercus Rubra','2', 1, 1, 10, 'Regulares', NULL);
CALL InsertTree(32, 'Encino Rojo', 'Quercus Rubra','2', 1, 3, 12, 'Buenas', NULL);
CALL InsertTree(33, 'Encino', 'Quercus Rubra','1.5', 1, 1.5, 10, 'Buenas', NULL);
CALL InsertTree(34, 'Laurel de la India', 'Ficus microcarpa','2', 1, 1, 10, 'Malas', NULL);
CALL InsertTree(35, 'Encino Rojo', 'Quercus Rubra','4', 3, 4, 18, 'Buenas', NULL);
CALL InsertTree(36, 'Encino Rojo', 'Quercus Rubra','4', 4, 5, 20, 'Buenas', NULL);
CALL InsertTree(37, 'Aacahuita', 'Blepharocalyx salicifolius','6', 4, 3, 22, 'Buenas', NULL);
CALL InsertTree(38, 'Encino Rojo', 'Quercus Rubra ','6', 5, 5, 15, 'Buenas', NULL);
CALL InsertTree(39, 'Encino', 'Quercus','3', 2, 3, 15, 'Buenas', NULL);
CALL InsertTree(40, 'Encino', 'Quercus','3', 4, 4, 17, 'Buenas', NULL);
CALL InsertTree(41, 'Tepehuaje', 'Lysiloma acapulquense','12', 10, 9, 43, 'Buenas', NULL);
CALL InsertTree(42, 'Tulia', 'Thuja accidentalis','20', 4, 6, 17, 'Regulares', NULL);
CALL InsertTree(43, 'Tulia', 'Thuja accidentalis','20', 4, 6, 17, 'Regulares', NULL);
CALL InsertTree(44, 'Pirul Mexicano', 'Schinus molle','6', 8, 6, 27, 'Regulares', NULL);
CALL InsertTree(45, 'Potro', 'Equus ferus caballus','7', 3, 7, 27, 'Buenas', NULL);
CALL InsertTree(46, 'Encino', 'Quercus','6', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(47, 'Encino', 'Quercus','6', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(48, 'Ebano', 'Ebenopsis ebano','7', 8, 6, 29, 'Buenas', NULL);
CALL InsertTree(49, 'Encino', 'Quercus','7', 6, 5, 27, 'Regulares', 'Daños en la corteza');
CALL InsertTree(50, 'Pino', 'Pinus sylvestris','16', 8, 10, 51, 'Buenas', NULL);
CALL InsertTree(51, 'Limon', 'Citrus limon','11', 5, 5, 32, 'Buenas', 'No presenta follaje');
CALL InsertTree(52, 'Sombrilla Japonesa', 'Koelreuteria paniculata','6', 4, 4, 23, 'Buenas', NULL);
CALL InsertTree(53, 'Sombrilla Japonesa', 'Koelreuteria paniculata','3', 1, 5, 16, 'Regulares', NULL);
CALL InsertTree(54, 'Encino', 'Quercus','7', 5, 6, 27, 'Buenas', NULL);
CALL InsertTree(55, 'Sombrilla Japonesa', 'Koelreuteria paniculata','8', 6, 6, 30, 'Regulares', NULL);
CALL InsertTree(56, 'Encino', 'Quercus','7', 7, 6, 28, 'Buenas', NULL);
CALL InsertTree(57, 'Limon', 'Citrus limon','6', 5, 4, 23, 'Buenas', NULL);
CALL InsertTree(58, 'Sombrilla Japonesa', 'Koelreuteria paniculata','1', 1, 2, 9, 'Buenas', NULL);
CALL InsertTree(59, 'Encino', 'Quercus','8', 8, 6, 31, 'Buenas', NULL);
CALL InsertTree(60, 'Encino', 'Quercus','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(61, 'Potro', 'Equus ferus caballus','10', 6, 7, 35, 'Regulares', NULL);
CALL InsertTree(62, 'Encino', 'Quercus','1.5', 1, 3.5, 12, 'Buenas', NULL);
CALL InsertTree(63, 'Encino', 'Quercus','2', 1, 3, 12, 'Regulares', 'Poco follaje');
CALL InsertTree(64, 'Naranjo', 'Citrus sinensis','7', 3, 3, 23, 'Buenas', NULL);
CALL InsertTree(65, 'Naranjo', 'Citrus sinensis','7', 3, 3, 23, 'Buenas', NULL);
CALL InsertTree(66, 'Encino', 'Quercus','8', 7, 6, 30, 'Buenas', NULL);
CALL InsertTree(67, 'Naranjo', 'Citrus sinensis','6', 3, 3, 21, 'Buenas', NULL);
CALL InsertTree(68, 'Naranjo', 'Citrus sinensis','4', 1, 2, 15, 'Malas', NULL);
CALL InsertTree(69, 'Pino', 'Pinus sylvestris','30', 12, 11, 82, 'Buenas', NULL);
CALL InsertTree(70, 'Fresno', 'Fraxinus excelsior','10', 8, 6, 35, 'Regulares', NULL);
CALL InsertTree(71, 'Palo Blanco', 'Calycophyllum multiflorum','3', 3, 3, 15, 'Buenas', NULL);
CALL InsertTree(72, 'Fresno', 'Fraxinus excelsior','9', 8, 7, 34, 'Buenas', NULL);
CALL InsertTree(73, 'Fresno', 'Fraxinus excelsior','6', 9, 6, 26, 'Buenas', NULL);
CALL InsertTree(74, 'Fresno', 'Fraxinus excelsior','16', 10, 6, 48, 'Buenas', NULL);
CALL InsertTree(75, 'Fresno', 'Fraxinus excelsior','6', 1, 3, 20, 'Malas', NULL);
CALL InsertTree(76, 'Palo Blanco', 'Calycophyllum multiflorum','5', 1, 2, 15, 'Regulares', NULL);
CALL InsertTree(77, 'Encino', 'Quercus','2', 0.5, 0.5, 9, 'Malas', 'Fuste quemado');
CALL InsertTree(78, 'Palo Blanco', 'Calycophyllum multiflorum','3', 4, 3, 16, 'Buenas', NULL);
CALL InsertTree(79, 'Fresno', 'Fraxinus excelsior','10', 6, 5, 33, 'Malas', NULL);
CALL InsertTree(80, 'Anacua', 'Ehretia anacua','5', 6, 5, 23, 'Buenas', NULL);
CALL InsertTree(81, 'Ebano', 'Ebenopsis ebano','10', 8, 7, 36, 'Buenas', NULL);
CALL InsertTree(82, 'Ebano', 'Ebenopsis ebano','7', 8, 6, 29, 'Buenas', NULL);
CALL InsertTree(83, 'Encino', 'Quercus','7', 8, 6, 29, 'Buenas', NULL);
CALL InsertTree(84, 'Encino Rojo', 'Quercus Rubra','3', 1.5, 5, 16, 'Buenas', NULL);
CALL InsertTree(85, 'Encino', 'Quercus','2.5', 2, 5, 16, 'Regulares', NULL);
CALL InsertTree(86, 'Fresno', 'Fraxinus excelsior','16', 8, 7, 48, 'Regulares', NULL);
CALL InsertTree(87, 'Fresno', 'Fraxinus excelsior','22', 10, 8, 62, 'Regulares', NULL);
CALL InsertTree(88, 'Fresno', 'Fraxinus excelsior','9', 1, 6, 29, 'Malas', NULL);
CALL InsertTree(89, 'Fresno', 'Fraxinus excelsior','12', 8, 6, 39, 'Malas', NULL);
CALL InsertTree(90, 'Fresno', 'Fraxinus excelsior','25', 12, 9, 70, 'Regulares', NULL);
CALL InsertTree(91, 'Palo Blanco', 'Calycophyllum multiflorum','7', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(92, 'Fresno', 'Fraxinus excelsior','13', 10, 8, 44, 'Regulares', NULL);
CALL InsertTree(93, 'Ebano', 'Ebenopsis ebano','11', 8, 7, 38, 'Buenas', NULL);
CALL InsertTree(94, 'Ebano Bur', 'Ebenopsis ebano','10', 6, 6, 34, 'Buenas', NULL);
CALL InsertTree(95, 'Palo Blanco', 'Calycophyllum multiflorum','4', 6, 5, 21, 'Buenas', NULL);
CALL InsertTree(96, 'Fresno', 'Fraxinus excelsior','9', 8, 8, 35, 'Regulares', NULL);
CALL InsertTree(97, 'Palo Blanco', 'Calycophyllum multiflorum','4', 6, 5, 21, 'Regulares', NULL);
CALL InsertTree(98, 'Fresno', 'Fraxinus excelsior','2', 2, 4, 14, 'Regulares', NULL);
CALL InsertTree(99, 'Encino Roble', 'Quercus','6', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(100, 'Encino', 'Quercus','9', 10, 6, 34, 'Buenas', NULL);
CALL InsertTree(101, 'Nogal', 'Junglans regia','5', 5, 5, 22, 'Buenas', NULL);
CALL InsertTree(102, 'Huamuchil', 'Pithecellobium dulce','16', 7, 6, 46, 'Buenas', NULL);
CALL InsertTree(103, 'Fresno', 'Fraxinus excelsior','2', 3, 4, 16, 'Malas', NULL);
CALL InsertTree(104, 'Encino', 'Quercus','4', 4, 5, 20, 'Buenas', NULL);
CALL InsertTree(105, 'Fresno', 'Fraxinus excelsior','5', 4, 4, 21, 'Malas', NULL);
CALL InsertTree(106, 'Fresno', 'Fraxinus excelsior','23', 8, 64, 61, 'Buenas', NULL);
CALL InsertTree(107, 'Ebano', 'Ebenopsis ebano','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(108, 'Encino', 'Quercus','9', 6, 6, 32, 'Buenas', NULL);
CALL InsertTree(109, 'Encino', 'Quercus','7', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(110, 'Fresno', 'Fraxinus excelsior','12', 6, 7, 30, 'Regulares', NULL);
CALL InsertTree(111, 'Encino', 'Quercus','9', 6, 6, 32, 'Buenas', NULL);
CALL InsertTree(112, 'Encino', 'Quercus','10', 7, 6, 34, 'Regulares', NULL);
CALL InsertTree(113, 'Fresno', 'Fraxinus excelsior','14', 6, 5, 41, 'Malas', NULL);
CALL InsertTree(114, 'Fresno', 'Fraxinus excelsior','5-3-3', 3, 5, 21, 'Regulares', NULL);
CALL InsertTree(115, 'Fresno', 'Fraxinus excelsior','9', 5, 5, 30, 'Regulares', NULL);
CALL InsertTree(116, 'Palo Blanco', 'Calycophyllum multiflorum','9', 8, 6, 33, 'Malas', NULL);
CALL InsertTree(117, 'Tulia', 'Thuja accidentalis','4', 6, 6, 22, 'Regulares', NULL);
CALL InsertTree(118, 'Tulia', 'Thuja accidentalis','4', 6, 6, 22, 'Regulares', NULL);
CALL InsertTree(119, 'Tulia', 'Thuja accidentalis','4', 6, 6, 22, 'Regulares', NULL);
CALL InsertTree(120, 'Tulia', 'Thuja accidentalis','4', 6, 6, 22, 'Regulares', NULL);
CALL InsertTree(121, 'Aacahuita', 'Blepharocalyx salicifolius','6', 6, 3, 23, 'Regulares', NULL);
CALL InsertTree(122, 'Fresno', 'Fraxinus excelsior','6-7', 8, 6, 29, 'Buenas', NULL);
CALL InsertTree(123, 'Aacahuita', 'Blepharocalyx salicifolius','4', 4, 3, 18, 'Buenas', NULL);
CALL InsertTree(124, 'Aacahuita', 'Blepharocalyx salicifolius','5-4-4', 6, 4, 22, 'Regulares', NULL);
CALL InsertTree(125, 'Alamo', 'Populus alba','17', 10, 8, 52, 'Buenas', NULL);
CALL InsertTree(126, 'Aacahuita', 'Blepharocalyx salicifolius','6', 5, 3.5, 23, 'Buenas', NULL);
CALL InsertTree(127, 'Encino', 'Quercus','5', 5, 5, 22, 'Buenas', NULL);
CALL InsertTree(128, 'Encino', 'Quercus','6', 5, 5, 23, 'Buenas', NULL);
CALL InsertTree(129, 'Ebano', 'Ebenopsis ebano','7', 7, 7, 29, 'Buenas', NULL);
CALL InsertTree(130, 'Encino', 'Quercus','3', 3, 3, 15, 'Regulares', NULL);
CALL InsertTree(131, 'Palma Washingtonia', 'Washingtonia robusta','14', 2, 12, 46, 'Regulares', NULL);
CALL InsertTree(132, 'Sombrilla Japonesa', 'Koelreuteria paniculata','8', 8, 7, 32, 'Buenas', NULL);
CALL InsertTree(133, 'Encino', 'Quercus','6', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(134, 'Anacua', 'Ehretia anacua','7', 4, 5, 26, 'Buenas', NULL);
CALL InsertTree(135, 'Potro', 'Equus ferus caballus','9', 4, 5, 30, 'Regulares', NULL);
CALL InsertTree(136, 'Naranjo', 'Citrus sinensis','3-2-2', 3, 3, 15, 'Regulares', NULL);
CALL InsertTree(137, 'Fresno', 'Fraxinus excelsior','20', 9, 6, 55, 'Malas', NULL);
CALL InsertTree(138, 'Fresno', 'Fraxinus excelsior','4-3-3', 5, 5, 20, 'Regulares', NULL);
CALL InsertTree(139, 'Fresno', 'Fraxinus excelsior','20', 8, 7, 56, 'Malas', NULL);
CALL InsertTree(140, 'Fresno', 'Fraxinus excelsior','10', 6, 7, 35, 'Malas', NULL);
CALL InsertTree(141, 'Arbol Seco', 'Sin nombre','13', 4, 8, 41, 'Seco', 'Seco');
CALL InsertTree(142, 'Pino', 'Pinus sylvestris','10', 8, 8, 37, 'Regulares', NULL);
CALL InsertTree(143, 'Pino', 'Pinus sylvestris','15-8', 9, 9, 48, 'Buenas', NULL);
CALL InsertTree(144, 'Eucalipto', 'Eucalyptus globulus','26', 10, 12, 74, 'Buenas', NULL);
CALL InsertTree(145, 'Eucalipto', 'Eucalyptus globulus','19', 10, 12, 60, 'Buenas', NULL);
CALL InsertTree(146, 'Pino', 'Pinus sylvestris','7', 5, 8, 29, 'Regulares', NULL);
CALL InsertTree(147, 'Pino', 'Pinus sylvestris','9', 4, 7, 32, 'Buenas', NULL);
CALL InsertTree(148, 'Pino', 'Pinus sylvestris','12-6', 6, 8, 40, 'Buenas', NULL);
CALL InsertTree(149, 'Fresno', 'Fraxinus excelsior','6', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(150, 'Encino', 'Quercus','15-17', 7, 8, 46, 'Regulares', NULL);
CALL InsertTree(151, 'Nogal', 'Junglans regia','6', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(152, 'Encino', 'Quercus','9', 7, 6, 32, 'Buenas', NULL);
CALL InsertTree(153, 'Encino', 'Quercus','7', 4, 5, 26, 'Buenas', NULL);
CALL InsertTree(154, 'Encino', 'Quercus','9', 8, 6, 33, 'Buenas', NULL);
CALL InsertTree(155, 'Encino', 'Quercus','6', 5, 6, 25, 'Buenas', NULL);
CALL InsertTree(156, 'Encino', 'Quercus','17', 12, 9, 54, 'Regulares', NULL);
CALL InsertTree(157, 'Encino Rojo', 'Quercus rubra','7', 4, 5, 26, 'Buenas', NULL);
CALL InsertTree(158, 'Encino Rojo', 'Quercus rubra','12', 8, 7, 40, 'Buenas', NULL);
CALL InsertTree(159, 'Ebano', 'Ebenopsis ebano','5', 6, 4, 22, 'Buenas', NULL);
CALL InsertTree(160, 'Encino', 'Quercus','7', 6, 5, 27, 'Regulares', NULL);
CALL InsertTree(161, 'Fresno', 'Fraxinus excelsior','23', 10, 7, 63, 'Malas', NULL);
CALL InsertTree(162, 'Palo Blanco', 'Calycophyllum multiflorum','9', 8, 7, 34, 'Regulares', NULL);
CALL InsertTree(163, 'Nogal', 'Junglans regia','10', 10, 7, 37, 'Regulares', NULL);
CALL InsertTree(164, 'Nogal', 'Junglans regia','25', 12, 10, 71, 'Buenas', NULL);
CALL InsertTree(165, 'Fresno', 'Fraxinus excelsior','18-14', 10, 8, 46, 'Malas', NULL);
CALL InsertTree(166, 'Palo Blanco', 'Calycophyllum multiflorum','6', 4, 4, 23, 'Regulares', 'Mala ubicación quitar');
CALL InsertTree(167, 'Encino Roble', 'Quercus','3', 3, 4, 16, 'Buenas', NULL);
CALL InsertTree(168, 'Alamo Sicomoro', 'Ficus sycomorus','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(169, 'Nogal', 'Junglans regia','17', 6, 6, 48, 'Regulares', NULL);
CALL InsertTree(170, 'Fresno', 'Fraxinus excelsior','17', 10, 6, 50, 'Malas', NULL);
CALL InsertTree(171, 'Fresno', 'Fraxinus excelsior','31', 8, 7, 78, 'Malas', NULL);
CALL InsertTree(172, 'Fresno', 'Fraxinus excelsior','27', 9, 7, 70, 'Malas', NULL);
CALL InsertTree(173, 'Fresno', 'Fraxinus excelsior','37', 8, 10, 93, 'Malas', NULL);
CALL InsertTree(174, 'Fresno', 'Fraxinus excelsior','23', 10, 8, 64, 'Malas', NULL);
CALL InsertTree(175, 'Fresno', 'Fraxinus excelsior','12', 6, 6, 38, 'Malas', NULL);
CALL InsertTree(176, 'Encino', 'Quercus','1.5', 2, 5, 14, 'Buenas', NULL);
CALL InsertTree(177, 'Fresno', 'Fraxinus excelsior','14', 10, 6, 44, 'Malas', NULL);
CALL InsertTree(178, 'Granado', 'Punica granatum','2', 4, 4, 15, 'Regulares', NULL);
CALL InsertTree(179, 'Tulia', 'Thuja accidentalis','7', 3, 4, 24, 'Buenas', NULL);
CALL InsertTree(180, 'Encino', 'Quercus','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(181, 'Encino', 'Quercus','13', 8, 6, 41, 'Buenas', NULL);
CALL InsertTree(182, 'Anacua', 'Ehretia anacua','7', 6, 6, 28, 'Regulares', NULL);
CALL InsertTree(183, 'Trueno', 'Ligustrum lucidum','7-7-5', 7, 7, 29, 'Regulares', NULL);
CALL InsertTree(184, 'Limon', 'Citrus limon','7-5', 8, 6, 29, 'Regulares', NULL);
CALL InsertTree(185, 'Limon', 'Citrus limon','5', 4, 4, 21, 'Regulares', NULL);
CALL InsertTree(186, 'Palo Blanco', 'Calycophyllum multiflorum','7', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(187, 'Anacua', 'Ehretia anacua','10', 8, 7, 26, 'Buenas', NULL);
CALL InsertTree(188, 'Encino', 'Quercus','12', 9, 8, 41, 'Buenas', NULL);
CALL InsertTree(189, 'Encino', 'Quercus','12', 10, 7, 41, 'Buenas', NULL);
CALL InsertTree(190, 'Potro', 'Equus ferus caballus','12', 10, 6, 40, 'Regulares', NULL);
CALL InsertTree(191, 'Encino', 'Quercus','7', 6, 5, 27, 'Regulares', NULL);
CALL InsertTree(192, 'Pingüica', 'Arctostaphylos pungens','4-3-2', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(193, 'Naranjo', 'Citrus sinensis','3', 3, 4, 16, 'Regulares', NULL);
CALL InsertTree(194, 'Fresno', 'Fraxinus excelsior','40', 10, 7, 97, 'Malas', NULL);
CALL InsertTree(195, 'Alamo Americano', 'Populus deltoides Marshall','3-3-2', 3, 3, 15, 'Buenas', 'Invasivo quitar');
CALL InsertTree(196, 'Naranjillo', 'Citronella mucronata ','5', 4, 4, 21, 'Buenas', NULL);
CALL InsertTree(197, 'Naranjillo', 'Citronella mucronata ','2', 3, 3, 15, 'Regulares', NULL);
CALL InsertTree(198, 'Pingüica', 'Arctostaphylos pungens','3', 2, 2, 14, 'Regulares', NULL);
CALL InsertTree(199, 'Aacahuita', 'Blepharocalyx salicifolius','6', 5, 4, 23, 'Buenas', NULL);
CALL InsertTree(200, 'Encino', 'Quercus','7', 6, 5, 27, 'Regulares', NULL);
CALL InsertTree(201, 'Sombrilla Japonesa', 'Koelreuteria paniculata','10', 10, 7, 37, 'Buenas', NULL);
CALL InsertTree(202, 'Limon', 'Citrus limon','7', 6, 5, 27, 'Regulares', NULL);
CALL InsertTree(203, 'Fresno', 'Fraxinus excelsior','23', 8, 7, 62, 'Regulares', NULL);
CALL InsertTree(204, 'Anacua', 'Ehretia anacua','1', 1, 2, 9, 'Buenas', NULL);
CALL InsertTree(205, 'Anacua', 'Ehretia anacua','15', 6, 6, 44, 'Regulares', NULL);
CALL InsertTree(206, 'Encino', 'Quercus','9', 6, 5, 31, 'Buenas', NULL);
CALL InsertTree(207, 'Encino', 'Quercus','4', 3, 5, 19, 'Buenas', NULL);
CALL InsertTree(208, 'Encino', 'Quercus','9', 10, 6, 34, 'Buenas', NULL);
CALL InsertTree(209, 'Encino', 'Quercus','7', 5, 5, 26, 'Buenas', NULL);
CALL InsertTree(210, 'Encino', 'Quercus','9', 8, 7, 33, 'Buenas', NULL);
CALL InsertTree(211, 'Mezquite', 'Prosopis laevigata','10', 10, 6, 36, 'Regulares', NULL);
CALL InsertTree(212, 'Chapote Amarillo', 'Diospyros texana','4', 5, 3.5, 19, 'Regulares', NULL);
CALL InsertTree(213, 'Ebano', 'Ebenopsis ebano','3', 3, 5, 17, 'Regulares', NULL);
CALL InsertTree(214, 'Encino Roble', 'Quercus','8', 8, 9, 34, 'Buenas', NULL);
CALL InsertTree(215, 'Alamo Sicomoro', 'Ficus sycomorus','1', 1, 2, 9, 'Malas', NULL);
CALL InsertTree(216, 'Encino', 'Quercus','4', 2, 4, 18, 'Buenas', NULL);
CALL InsertTree(217, 'Encino', 'Quercus','5', 3, 5, 21, 'Buenas', NULL);
CALL InsertTree(218, 'Encino', 'Quercus','1', 1, 1, 8, 'Regulares', NULL);
CALL InsertTree(219, 'Mezquite', 'Prosopis laevigata','8', 8, 5, 30, 'Buenas', NULL);
CALL InsertTree(220, 'Ebano', 'Ebenopsis ebano','3', 3, 4, 16, 'Buenas', NULL);
CALL InsertTree(221, 'Alamo Sicomoro', 'Ficus sycomorus','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(222, 'Encino', 'Quercus','2', 1, 3, 12, 'Regulares', NULL);
CALL InsertTree(223, 'Naranjo', 'Citrus sinensis','2', 0.5, 1, 10, 'Malas', NULL);
CALL InsertTree(224, 'Pino Rompe Viento', 'Pinus rompe viento','7-9', 6, 7, 31, 'Regulares', NULL);
CALL InsertTree(225, 'Pino', 'Pinus sylvestris','15', 8, 7, 46, 'Regulares', NULL);
CALL InsertTree(226, 'Mezquite', 'Prosopis laevigata','3', 4, 3, 16, 'Regulares', NULL);
CALL InsertTree(227, 'Anacua', 'Ehretia anacua','6', 6, 5, 25, 'Buenas', NULL);
CALL InsertTree(228, 'Encino', 'Quercus','7', 5, 6, 27, 'Buenas', NULL);
CALL InsertTree(229, 'Encino', 'Quercus','9', 6, 6, 32, 'Buenas', NULL);
CALL InsertTree(230, 'Chapote Amarillo', 'Diospyros texana','5-4', 4, 4, 21, 'Regulares', NULL);
CALL InsertTree(231, 'Mezquite', 'Prosopis laevigata','10', 10, 7, 37, 'Regulares', NULL);
CALL InsertTree(232, 'Palo Blanco', 'Calycophyllum multiflorum','6', 8, 5, 26, 'Buenas', NULL);
CALL InsertTree(233, 'Ebano', 'Ebenopsis ebano','3', 3, 4, 16, 'Buenas', NULL);
CALL InsertTree(234, 'Anacua', 'Ehretia anacua','9-7', 6, 6, 32, 'Regulares', NULL);
CALL InsertTree(235, 'Encino', 'Quercus','2.5', 1, 2, 12, 'Regulares', NULL);
CALL InsertTree(236, 'Ebano', 'Ebenopsis ebano','7', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(237, 'Ebano', 'Ebenopsis ebano','6', 6, 5, 25, 'Buenas', NULL);
CALL InsertTree(238, 'Fresno', 'Fraxinus excelsior','12', 5, 7, 38, 'Malas', NULL);
CALL InsertTree(239, 'Ebano', 'Ebenopsis ebano','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(240, 'Encino', 'Quercus','2', 2, 3, 13, 'Buenas', NULL);
CALL InsertTree(241, 'Encino Rojo', 'Quercus','3', 3, 5, 17, 'Buenas', NULL);
CALL InsertTree(242, 'Encino', 'Quercus','7', 4, 4, 25, 'Buenas', NULL);
CALL InsertTree(243, 'Encino', 'Quercus','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(244, 'Anacua', 'Ehretia anacua','9', 5, 5, 30, 'Regulares', NULL);
CALL InsertTree(245, 'Anacua', 'Ehretia anacua','6-7', 7, 5, 27, 'Regulares', NULL)
CALL InsertTree(246, 'Anacua', 'Ehretia anacua','18', 8, 7, 52, 'Regulares', NULL);
CALL InsertTree(247, 'Huizache', 'Vachella farnesiana','17', 8, 8, 51, 'Regulares', NULL);
CALL InsertTree(248, 'Palo Blanco', 'Calycophyllum multiflorum','9', 6, 6, 32, 'Malas', 'a 3 mts de barda');
CALL InsertTree(249, 'Tepehuaje', 'Lysiloma acapulquense','8', 4, 7, 30, 'Regulares', 'a 2 mts de barda');
CALL InsertTree(250, 'Nogal', 'Junglans regia','2', 1, 2, 11, 'Regulares', NULL);
CALL InsertTree(251, 'Anacua', 'Ehretia anacua','5', 7, 7, 25, 'Regulares', 'a 3 mts de barda');
CALL InsertTree(252, 'Tepehuaje', 'Lysiloma acapulquense','7', 6, 6, 28, 'Regulares', 'a 3 mts de barda');
CALL InsertTree(253, 'Retama', 'Retama sphaerocarpa','10-4-4', 5, 5, 32, 'Mala', 'Doblado hacia el vecino');
CALL InsertTree(254, 'Tepehuaje', 'Lysiloma acapulquense','4-3-3', 4, 5, 20, 'Regulares', 'a 4 mts de barda');
CALL InsertTree(255, 'Tepehuaje', 'Lysiloma acapulquense','4', 2, 6, 20, 'Regulares', 'a 4 mts de barda inclinado') 
CALL InsertTree(256, 'Tepehuaje', 'Lysiloma acapulquense','4', 2, 6, 20, 'Regulares', 'a 4 mts de barda inclinado')
CALL InsertTree(257, 'Tepehuaje', 'Lysiloma acapulquense','4', 2, 6, 20, 'Regulares', 'a 4 mts de barda inclinado') 
CALL InsertTree(258, 'Anacua', 'Ehretia anacua','4', 2, 3, 17, 'Regulares', 'a 3 mts de barda inclinado');
CALL InsertTree(259, 'Tepehuaje', 'Lysiloma acapulquense','4', 2, 4, 20, 'Regulares', 'a 4 mts de barda inclinado') 
CALL InsertTree(260, 'Tepehuaje', 'Lysiloma acapulquense','4', 3, 5, 19, 'Regulares', 'a 4 mts de barda inclinado') 
CALL InsertTree(261, 'Tepehuaje', 'Lysiloma acapulquense','4', 3, 4, 18, 'Regulares', 'a 4 mts de barda inclinado') 
CALL InsertTree(262, 'Huizache', 'Vachella farnesiana','18-12', 9, 7, 52, 'Regulares', NULL);
CALL InsertTree(263, 'Canelo', 'Drimys winteri','5-4-4-4', 6, 7, 24, 'Regulares', NULL);
CALL InsertTree(264, 'Tepehuaje', 'Lysiloma acapulquense','3', 2, 6, 41, 'Regulares', NULL);
CALL InsertTree(265, 'Tepehuaje', 'Lysiloma acapulquense','11', 3, 7, 35, 'Malas', NULL);
CALL InsertTree(266, 'Tepehuaje', 'Lysiloma acapulquense','7', 2, 7, 27, 'Regulares', NULL);
CALL InsertTree(267, 'Tepehuaje', 'Lysiloma acapulquense','7', 4, 7, 28, 'Regulares', NULL);
CALL InsertTree(268, 'Tepehuaje', 'Lysiloma acapulquense','5', 3, 7, 23, 'Regulares', NULL);
CALL InsertTree(269, 'Tepehuaje', 'Lysiloma acapulquense','7', 4, 7, 28, 'Regulares', NULL);
CALL InsertTree(270, 'Tepehuaje', 'Lysiloma acapulquense','5-7', 3, 6, 22, 'Regulares', NULL);
CALL InsertTree(271, 'Anacua', 'Ehretia anacua','3', 3, 4, 16, 'Regulares', NULL);
CALL InsertTree(272, 'Tepehuaje', 'Lysiloma acapulquense','3', 4, 7, 20, 'Regulares', 'Ente fustes secos');
CALL InsertTree(273, 'Tepehuaje', 'Lysiloma acapulquense','4-3', 3, 6, 20, 'Regulares', NULL);
CALL InsertTree(274, 'Tepehuaje', 'Lysiloma acapulquense','7', 4, 8, 29, 'Regulares', NULL);
CALL InsertTree(275, 'Fresno', 'Fraxinus excelsior','2-7', 5, 7, 30, 'Regulares', NULL);
CALL InsertTree(276, 'Tepehuaje', 'Lysiloma acapulquense','10', 8, 7, 36, 'Regulares', NULL);
CALL InsertTree(277, 'Canelo', 'Drimys winteri','8', 6, 6, 30, 'Regulares', NULL);
CALL InsertTree(278, 'Fresno', 'Fraxinus excelsior','8', 6, 6, 30, 'Regulares', NULL);
CALL InsertTree(279, 'Tepehuaje', 'Lysiloma acapulquense','4', 4, 4, 19, 'Regulares', NULL);
CALL InsertTree(280, 'Anacua', 'Ehretia anacua','6', 4, 5, 24, 'Regulares', NULL);
CALL InsertTree(281, 'Tepehuaje', 'Lysiloma acapulquense','4', 4, 4, 19, 'Regulares', NULL);
CALL InsertTree(282, 'Tepehuaje', 'Lysiloma acapulquense','4', 3, 5, 19, 'Regulares', NULL);
CALL InsertTree(283, 'Tepehuaje', 'Lysiloma acapulquense','4', 3, 5, 19, 'Regulares', NULL);
CALL InsertTree(284, 'Fresno', 'Fraxinus excelsior','4', 5, 7, 22, 'Regulares', NULL);
CALL InsertTree(285, 'Fresno', 'Fraxinus excelsior','7', 4, 8, 29, 'Regulares', NULL);
CALL InsertTree(286, 'Fresno', 'Fraxinus excelsior','6', 4, 7, 26, 'Regulares', NULL);
CALL InsertTree(287, 'Fresno', 'Fraxinus excelsior','9', 4, 7, 32, 'Regulares', NULL);
CALL InsertTree(288, 'Fresno', 'Fraxinus excelsior','6', 8, 3, 24, 'Regulares', NULL);
CALL InsertTree(289, 'Fresno', 'Fraxinus excelsior','6', 3, 8, 26, 'Regulares', NULL);
CALL InsertTree(290, 'Canelo', 'Drimys winteri','6', 5, 6, 25, 'Regulares', NULL);
CALL InsertTree(291, 'Mezquite Nativo', 'Prosopis laevigata','5', 5, 4, 21, 'Regulares', NULL);
CALL InsertTree(292, 'Canelo', 'Drimys winteri','7-4', 4, 6, 27, 'Buenas', NULL);
CALL InsertTree(293, 'Canelo', 'Drimys winteri','5', 4, 6, 23, 'Regulares', NULL);
CALL InsertTree(294, 'Tepehuaje', 'Lysiloma acapulquense','8', 4, 7, 30, 'Regulares', NULL);
CALL InsertTree(295, 'Tepehuaje', 'Lysiloma acapulquense','5', 4, 7, 24, 'Regulares', NULL);
CALL InsertTree(296, 'Fresno', 'Fraxinus excelsior','7', 5, 6, 27, 'Regulares', NULL);
CALL InsertTree(297, 'Tepehuaje', 'Lysiloma acapulquense','7-3', 4, 6, 27, 'Regulares', NULL);
CALL InsertTree(298, 'Mezquite Nativo', 'Prosopis laevigata','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(299, 'Retama', 'Retama sphaerocarpa','4', 4, 4, 19, 'Regulares', NULL);
CALL InsertTree(300, 'Fresno', 'Fraxinus excelsior','3', 3, 4, 16, 'Regulares', NULL);
CALL InsertTree(301, 'Nogal', 'Junglans regia','10', 7, 9, 37, 'Buenas', NULL);
CALL InsertTree(302, 'Canelo', 'Drimys winteri','7', 3, 7, 27, 'Regulares', 'casi acostado quitar');
CALL InsertTree(303, 'Encino', 'Quercus','8', 6, 5, 29, 'Regulares', NULL);
CALL InsertTree(304, 'Encino', 'Quercus','3', 3, 3, 15, 'Buenas', NULL);
CALL InsertTree(305, 'Aacahuita', 'Blepharocalyx salicifolius','3', 2, 2, 14, 'Buenas', NULL);
CALL InsertTree(306, 'Aacahuita', 'Blepharocalyx salicifolius','3', 2, 2, 14, 'Buenas', NULL);
CALL InsertTree(307, 'Encino Roble', 'Quercus','2.5', 1, 2, 12, 'Regulares', NULL);
CALL InsertTree(308, 'Retama', 'Retama sphaerocarpa','11-5', 4, 5, 12, 'Mala', NULL);
CALL InsertTree(309, 'Retama', 'Retama sphaerocarpa','17', 8, 7, 50, 'Regulares', NULL);
CALL InsertTree(310, 'Tepehuaje', 'Lysiloma acapulquense','4-4-3-3', 4, 6, 21, 'Regulares', NULL);
CALL InsertTree(311, 'Palo Blanco', 'Calycophyllum multiflorum','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(312, 'Palo Blanco', 'Calycophyllum multiflorum','5', 4, 4, 21, 'Buenas', NULL);
CALL InsertTree(313, 'Palo Blanco', 'Calycophyllum multiflorum','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(314, 'Palo Blanco', 'Calycophyllum multiflorum','6', 6, 4, 24, 'Buenas', NULL);
CALL InsertTree(315, 'Palo Blanco', 'Calycophyllum multiflorum','6', 6, 4, 24, 'Buenas', NULL);
CALL InsertTree(316, 'Palo Blanco', 'Calycophyllum multiflorum','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(317, 'Palo Blanco', 'Calycophyllum multiflorum','5', 6, 4, 22, 'Buenas', NULL);
CALL InsertTree(318, 'Palo Blanco', 'Calycophyllum multiflorum','3', 2, 3, 15, 'Buenas', NULL);
CALL InsertTree(319, 'Ebano', 'Ebenopsis ebano','3', 2, 3, 15, 'Buenas', NULL);
CALL InsertTree(320, 'Ebano', 'Ebenopsis ebano','2', 2, 3, 13, 'Regulares', NULL);
CALL InsertTree(321, 'Fresno', 'Fraxinus excelsior','4.5', 4, 4, 20, 'Buenas', NULL);
CALL InsertTree(322, 'Encino', 'Quercus','20', 12, 10, 61, 'Malas', NULL);
CALL InsertTree(323, 'Granado', 'Punica granatum','1', 6, 2, 12, 'Regulares', NULL);
CALL InsertTree(324, 'Naranjo', 'Citrus sinensis','3', 3, 4, 16, 'Regulares', NULL);
CALL InsertTree(325, 'Mezquite Chileno', 'Prosopis laevigata','7-4', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(326, 'Mezquite Chileno', 'Prosopis laevigata','6', 5, 4, 23, 'Buenas', NULL);
CALL InsertTree(327, 'Mezquite Chileno', 'Prosopis laevigata','7', 7, 6, 28, 'Buenas', NULL);
CALL InsertTree(328, 'Encino', 'Quercus','14', 8, 8, 45, 'Malas', NULL);
CALL InsertTree(329, 'Fresno', 'Fraxinus excelsior','3', 3, 4, 16, 'Regulares', NULL);
CALL InsertTree(330, 'Fresno', 'Fraxinus excelsior','3-2', 3, 3, 15, 'Regulares', NULL);
CALL InsertTree(331, 'Huizache', 'Vachella farnesiana','3', 2, 3, 15, 'Buenas', NULL);
CALL InsertTree(332, 'Encino', 'Quercus','25', 10, 10, 70, 'Malas', NULL);
CALL InsertTree(333, 'Fresno', 'Fraxinus excelsior','13', 9, 7, 42, 'Regulares', NULL);
CALL InsertTree(334, 'Nispero', 'Eriobotrya japonica','6-4', 6, 5, 25, 'Buenas', NULL);
CALL InsertTree(335, 'Fresno', 'Fraxinus excelsior','10-6', 10, 6, 36, 'Regulares', NULL);
CALL InsertTree(336, 'Nispero', 'Eriobotrya japonica','6', 6, 5, 25, 'Buenas', NULL);
CALL InsertTree(337, 'Fresno', 'Fraxinus excelsior','6-4-4', 8, 6, 27, 'Regulares', NULL);
CALL InsertTree(338, 'Canelo', 'Drimys winteri','8', 8, 8, 33, 'Regulares', NULL);
CALL InsertTree(339, 'Canelo', 'Drimys winteri','5', 4, 6, 23, 'Regulares', NULL);
CALL InsertTree(340, 'Canelo', 'Drimys winteri','7-5-4', 8, 6, 29, 'Regulares', NULL);
CALL InsertTree(341, 'Canelo', 'Drimys winteri','20', 10, 9, 59, 'Buenas', NULL);
CALL InsertTree(342, 'Sombrilla Japonesa', 'Koelreuteria paniculata','11', 10, 8, 40, 'Regulares', NULL);
CALL InsertTree(343, 'Bambu', 'Bambusa vulgaris','2', 4, 8, 29, 'Regulares', NULL);
CALL InsertTree(344, 'Anacua', 'Ehretia anacua','4-3-3', 5, 4, 19, 'Regulares', NULL);
CALL InsertTree(345, 'Sombrilla Japonesa', 'Koelreuteria paniculata','10', 7, 5, 33, 'Buenas', NULL);
CALL InsertTree(346, 'Sombrilla Japonesa', 'Koelreuteria paniculata','8-6', 6, 5, 29, 'Regulares', NULL);
CALL InsertTree(347, 'Sombrilla Japonesa', 'Koelreuteria paniculata','7', 4, 5, 26, 'Regulares', NULL);
CALL InsertTree(348, 'Fresno', 'Fraxinus excelsior','10', 6, 6, 34, 'Malas', 'Fuste hueco quitar');
CALL InsertTree(349, 'Palo Blanco', 'Calycophyllum multiflorum','4', 6, 5, 21, 'Buenas', NULL);
CALL InsertTree(350, 'Sombrilla Japonesa', 'Koelreuteria paniculata','8', 7, 4, 28, 'Buenas', NULL);
CALL InsertTree(351, 'Sombrilla Japonesa', 'Koelreuteria paniculata','8', 4, 4, 27, 'Malas', NULL);
CALL InsertTree(352, 'Sombrilla Japonesa', 'Koelreuteria paniculata','9', 6, 4, 30, 'Malas', NULL);
CALL InsertTree(353, 'Sombrilla Japonesa', 'Koelreuteria paniculata','3-2', 3, 4, 16, 'Malas', NULL);
CALL InsertTree(354, 'Anacua', 'Ehretia anacua','7', 5, 5, 26, 'Regulares', NULL);
CALL InsertTree(355, 'Sombrilla Japonesa', 'Koelreuteria paniculata','6', 3, 4, 22, 'Malas', NULL);
CALL InsertTree(356, 'Sombrilla Japonesa', 'Koelreuteria paniculata','7', 6, 5, 27, 'Regulares', NULL);
CALL InsertTree(357, 'Tepehuaje', 'Lysiloma acapulquense','6', 4, 7, 26, 'Regulares', 'a 20 cm de construccion');
CALL InsertTree(358, 'Sombrilla Japonesa', 'Koelreuteria paniculata','8', 6, 6, 30, 'Buenas', NULL);
CALL InsertTree(359, 'Sombrilla Japonesa', 'Koelreuteria paniculata','11', 8, 5, 36, 'Buenas', NULL);
CALL InsertTree(360, 'Ebano', 'Ebenopsis ebano','3', 2, 4, 16, 'Buenas', NULL);
CALL InsertTree(361, 'Ebano', 'Ebenopsis ebano','2', 1, 2, 11, 'Buenas', NULL);
CALL InsertTree(362, 'Palo Blanco', 'Calycophyllum multiflorum','2', 1, 3, 12, 'Buenas', NULL);
CALL InsertTree(363, 'Palo Blanco', 'Calycophyllum multiflorum','1', 1, 2, 9, 'Buenas', NULL);
CALL InsertTree(364, 'Fresno', 'Fraxinus excelsior','4-3', 4, 3, 18, 'Buenas', NULL);
CALL InsertTree(365, 'Retama', 'Retama sphaerocarpa','11', 10, 6, 38, 'Buenas', NULL);
CALL InsertTree(366, 'Palo Blanco', 'Calycophyllum multiflorum','3', 2, 2, 10, 'Buenas', NULL);
CALL InsertTree(367, 'Hierba del Potro', 'Caesalpinia mexicana','2', 3, 3, 13, 'Regulares', NULL);
CALL InsertTree(368, 'Huamuchil', 'Pithecellobium dulce','10', 3, 4, 30, 'Malas', NULL);
CALL InsertTree(369, 'Huamuchil', 'Pithecellobium dulce','14', 4, 6, 41, 'Malas', NULL);
CALL InsertTree(370, 'Huamuchil', 'Pithecellobium dulce','11', 3, 6, 34, 'Malas', NULL);
CALL InsertTree(371, 'Pata de Vaca', 'Bauhinia forficata','7', 4, 7, 28, 'Regulares', NULL);
CALL InsertTree(372, 'Pata de Vaca', 'Bauhinia forficata','6', 3, 7, 25, 'Regulares', NULL);
CALL InsertTree(373, 'Fresno', 'Fraxinus excelsior','13', 10, 7, 43, 'Buenas', NULL);
CALL InsertTree(374, 'Guayabo', 'Psidium guajava','6-4-4', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(375, 'Trueno', 'Ligustrum lucidum','7', 4, 4, 25, 'Malas', NULL);
CALL InsertTree(376, 'Pino', 'Pinus sylvestris','14', 3, 9, 43, 'Malas', NULL);
CALL InsertTree(377, 'Pata de Vaca', 'Bauhinia forficata','9-7-7', 6, 7, 33, 'Regulares', NULL);
CALL InsertTree(378, 'Naranjo', 'Citrus sinensis','4', 3, 2, 16, 'Buenas', NULL);
CALL InsertTree(379, 'Encino', 'Quercus','25', 12, 10, 70, 'Regulares', NULL);
CALL InsertTree(380, 'Ebano', 'Ebenopsis ebano','7', 7, 7, 29, 'Buenas', NULL);
CALL InsertTree(381, 'Durazno', 'Prunus perisca','3', 2, 2, 14, 'Buenas', NULL);
CALL InsertTree(382, 'Naranjo', 'Citrus sinensis','4', 6, 5, 21, 'Regulares', NULL);
CALL InsertTree(383, 'Pino', 'Pinus sylvestris','18', 4, 8, 51, 'Regulares', NULL);
CALL InsertTree(384, 'Palma Washingtonia', 'Washingtonia robusta','12', 2, 14, 44, 'Regulares', NULL);
CALL InsertTree(385, 'Pata de Vaca', 'Bauhinia forficata','9-6-4', 6, 7, 33, 'Regulares', NULL);
CALL InsertTree(386, 'Guayabo', 'Psidium guajava','4-4-3', 4, 4, 19, 'Regulares', NULL);
CALL InsertTree(387, 'Fresno', 'Fraxinus excelsior','14-8', 8, 6, 43, 'Regulares', NULL);
CALL InsertTree(388, 'Guayabo', 'Psidium guajava','5-4-4', 6, 6, 24, 'Regulares', NULL);
CALL InsertTree(389, 'Fresno', 'Fraxinus excelsior','8', 5, 5, 28, 'Malas', NULL);
CALL InsertTree(390, 'Fresno', 'Fraxinus excelsior','12', 8, 6, 39, 'Regulares', NULL);
CALL InsertTree(391, 'Fresno', 'Fraxinus excelsior','12', 8, 6, 39, 'Regulares', NULL);
CALL InsertTree(392, 'Fresno', 'Fraxinus excelsior','25', 12, 6, 67, 'Regulares', NULL);
CALL InsertTree(393, 'Fresno', 'Fraxinus excelsior','10', 10, 6, 36, 'Regulares', NULL);
CALL InsertTree(394, 'Fresno', 'Fraxinus excelsior','15', 10, 6, 46, 'Regulares', NULL);
CALL InsertTree(395, 'Sombrilla Japonesa', 'Koelreuteria paniculata','16', 10, 6, 48, 'Regulares', NULL);
CALL InsertTree(396, 'Fresno', 'Fraxinus excelsior','10', 6, 6, 34, 'Regulares', NULL);
CALL InsertTree(396, 'Fresno', 'Fraxinus excelsior','10', 6, 6, 34, 'Regulares', NULL);
CALL InsertTree(397, 'Fresno', 'Fraxinus excelsior','20', 12, 6, 57, 'Regulares', NULL);
CALL InsertTree(398, 'Fresno', 'Fraxinus excelsior','14', 10, 5, 43, 'Regulares', NULL);
CALL InsertTree(399, 'Pino', 'Pinus sylvestris','13', 8, 10, 45, 'Regulares', NULL);
CALL InsertTree(400, 'Pata de Vaca', 'Bauhinia forficata','9-9-7', 10, 8, 36, 'Regulares', NULL);
CALL InsertTree(401, 'Mezquite Nativo', 'Prosopis laevigata','8', 10, 8, 34, 'Buenas', NULL);
CALL InsertTree(402, 'Mezquite Chileno', 'Prosopis laevigata','7', 5, 5, 26, 'Regulares', NULL);
CALL InsertTree(403, 'Mezquite Chileno', 'Prosopis laevigata','6', 4, 7, 26, 'Regulares', 'Torcido');
CALL InsertTree(404, 'Naranjo', 'Citrus sinensis','4', 4, 3, 18, 'Buenas', NULL);
CALL InsertTree(405, 'Ebano', 'Ebenopsis ebano','2', 1, 3, 12, 'Buenas', NULL);
CALL InsertTree(406, 'Tepehuaje', 'Lysiloma acapulquense','4', 6, 5, 21, 'Buenas', NULL);
CALL InsertTree(407, 'Tepehuaje', 'Lysiloma acapulquense','5-4', 4, 6, 23, 'Regulares', NULL);
CALL InsertTree(408, 'Naranjo', 'Citrus sinensis','2', 2, 2, 12, 'Regulares', NULL);
CALL InsertTree(409, 'Tepehuaje', 'Lysiloma acapulquense','3', 2, 5, 17, 'Buenas', NULL);
CALL InsertTree(410, 'Naranjo', 'Citrus sinensis','4', 3, 3, 17, 'Buenas', NULL);
CALL InsertTree(411, 'Naranjo', 'Citrus sinensis','2', 2, 1.5, 11, 'Buenas', NULL);
CALL InsertTree(412, 'Tepehuaje', 'Lysiloma acapulquense','3', 6, 6, 20, 'Buenas', NULL);
CALL InsertTree(413, 'Tepehuaje', 'Lysiloma acapulquense','3', 5, 5, 18, 'Buenas', NULL);
CALL InsertTree(414, 'Naranjo', 'Citrus sinensis','2', 1, 1.5, 11, 'Regulares', NULL);
CALL InsertTree(415, 'Tepehuaje', 'Lysiloma acapulquense','4', 5, 5, 20, 'Buenas', NULL);
CALL InsertTree(416, 'Tepehuaje', 'Lysiloma acapulquense','4', 5, 5, 20, 'Buenas', NULL);
CALL InsertTree(417, 'Naranjo', 'Citrus sinensis','2', 2, 2, 12, 'Regulares', 'Pegados');
CALL InsertTree(418, 'Tepehuaje', 'Lysiloma acapulquense','4-2', 6, 6, 22, 'Buenas', 'Pegados');
CALL InsertTree(419, 'Tepehuaje', 'Lysiloma acapulquense','6', 6, 6, 26, 'Buenas', NULL);
CALL InsertTree(420, 'Tepehuaje', 'Lysiloma acapulquense','7', 6, 7, 29, 'Malas', NULL);
CALL InsertTree(421, 'Anacua', 'Ehretia anacua','2', 3, 2, 12, 'Buenas', NULL);
CALL InsertTree(422, 'Tepehuaje', 'Lysiloma acapulquense','4', 6, 7, 23, 'Regulares', 'Pegados');
CALL InsertTree(423, 'Naranjo', 'Citrus sinensis','2', 2, 2, 12, 'Regulares', 'Pegados');
CALL InsertTree(424, 'Anacua', 'Ehretia anacua','3', 4, 4, 17, 'Regulares', NULL);
CALL InsertTree(425, 'Tepehuaje', 'Lysiloma acapulquense','7', 5, 5, 26, 'Regulares', NULL);
CALL InsertTree(426, 'Naranjo', 'Citrus sinensis','5', 3, 5, 21, 'Buenas', NULL);
CALL InsertTree(427, 'Fresno', 'Fraxinus excelsior','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(428, 'Mezquite', 'Prosopis laevigata','6', 5, 5, 24, 'Buenas', NULL);
CALL InsertTree(429, 'Retama', 'Retama sphaerocarpa','10', 4, 6, 33, 'Malas', 'Quitar');
CALL InsertTree(430, 'Mezquite', 'Prosopis laevigata','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(431, 'Tepehuaje', 'Lysiloma acapulquense','7', 5, 5, 26, 'Regulares', '45° inclinación pegado a barda');
CALL InsertTree(432, 'Tepehuaje', 'Lysiloma acapulquense','8', 7, 8, 32, 'Buenas', NULL);
CALL InsertTree(433, 'Fresno', 'Fraxinus excelsior','7', 6, 6, 28, 'Regulares', NULL);
CALL InsertTree(434, 'Tepehuaje', 'Lysiloma acapulquense','8', 7, 8, 32, 'Regulares', '45° inclinacion');
CALL InsertTree(435, 'Tepehuaje', 'Lysiloma acapulquense','4', 4, 4, 19, 'Regulares', NULL);
CALL InsertTree(436, 'Encino', 'Quercus','2', 1, 2, 11, 'Buenas', NULL);
CALL InsertTree(437, 'Encino', 'Quercus','2', 1, 3, 12, 'Regulares', NULL);
CALL InsertTree(438, 'Tepehuaje', 'Lysiloma acapulquense','6-6-4-4', 6, 6, 26, 'Buenas', 'Brazo inclinado');
CALL InsertTree(439, 'Tepehuaje', 'Lysiloma acapulquense','3', 2, 3, 15, 'Regulares', NULL);
CALL InsertTree(440, 'Tepehuaje', 'Lysiloma acapulquense','3-3-2', 4, 4, 17, 'Regulares', 'Brazo inclinado');
CALL InsertTree(441, 'Palo Blanco', 'Calycophyllum multiflorum','3', 3, 4, 16, 'Regulares', NULL);
CALL InsertTree(442, 'Ebano', 'Ebenopsis ebano','2', 1, 3, 12, 'Regulares', NULL);
CALL InsertTree(443, 'Encino', 'Quercus','2', 1, 3, 12, 'Regulares', NULL);
CALL InsertTree(444, 'Palo Blanco', 'Calycophyllum multiflorum','3', 3, 4, 16, 'Regulares', NULL);
CALL InsertTree(445, 'Encino Rojo', 'Quercus rubra','2', 1, 2.5, 12, 'Buenas', NULL);
CALL InsertTree(446, 'Tepehuaje', 'Lysiloma acapulquense','6', 4, 4, 23, 'Buenas', NULL);
CALL InsertTree(447, 'Encino', 'Quercus','3', 1, 3, 14, 'Regulares', NULL);
CALL InsertTree(448, 'Encino', 'Quercus','2', 1, 2, 11, 'Malas', NULL);
CALL InsertTree(449, 'Tepehuaje', 'Lysiloma acapulquense','4-3', 5, 6, 21, 'Regulares', NULL);
CALL InsertTree(450, 'Ebano', 'Ebenopsis ebano','3', 3, 4, 16, 'Buenas', NULL);
CALL InsertTree(451, 'Ebano', 'Ebenopsis ebano','3', 2, 2, 14, 'Regulares', NULL);
CALL InsertTree(452, 'Ebano', 'Ebenopsis ebano','3', 3, 3, 15, 'Regulares', NULL);
CALL InsertTree(453, 'Pata de Vaca', 'Bauhinia forficata','15-6-6', 8, 7, 46, 'Buenas', NULL);
CALL InsertTree(454, 'Pata de Vaca', 'Bauhinia forficata','7', 5, 5, 26, 'Buenas', NULL);
CALL InsertTree(455, 'Naranjo', 'Citrus sinensis','2', 2, 1.5, 11, 'Regulares', NULL);
CALL InsertTree(456, 'Sombrilla Japonesa', 'Koelreuteria paniculata','17', 9, 8, 51, 'Buenas', NULL);
CALL InsertTree(457, 'Encino', 'Quercus','3', 2, 2.5, 14, 'Buenas', NULL);
CALL InsertTree(458, 'Ebano', 'Ebenopsis ebano','4', 4, 4, 16, 'Buenas', NULL);
CALL InsertTree(459, 'Ebano', 'Ebenopsis ebano','4', 4, 4, 16, 'Buenas', NULL);
CALL InsertTree(460, 'Encino', 'Quercus','2', 1, 3, 12, 'Regulares', NULL);
CALL InsertTree(461, 'Palo Blanco', 'Calycophyllum multiflorum','2', 2, 2, 12, 'Regulares', NULL);
CALL InsertTree(462, 'Encino Roble', 'Quercus','1', 0.5, 1.5, 8, 'Malas', NULL);
CALL InsertTree(463, 'Encino Rojo', 'Quercus rubra','2', 1, 1.5, 11, 'Regulares', NULL);
CALL InsertTree(464, 'Tepehuaje', 'Lysiloma acapulquense','4-5-6', 6, 6, 26, 'Regulares', 'Brazos 45° inclinados');
CALL InsertTree(465, 'Laurel de la India', 'Ficus microcarpa','3', 4, 3, 16, 'Regulares', 'Pegados');
CALL InsertTree(466, 'Tepehuaje', 'Lysiloma acapulquense','6', 4, 6, 25, 'Regulares', 'Pegados');
CALL InsertTree(467, 'Encino', 'Quercus','2', 3, 3, 13, 'Buenas', 'Pegados');
CALL InsertTree(468, 'Tepehuaje', 'Lysiloma acapulquense','3', 3, 4, 16, 'Regulares', 'Pegados');
CALL InsertTree(469, 'Naranjo', 'Citrus sinensis','3', 3, 3, 15, 'Regulares', NULL);
CALL InsertTree(470, 'Alamo Mexicano', 'Plantanus mexicana','15', 6, 6, 44, 'Buenas', NULL);
CALL InsertTree(471, 'Naranjo', 'Citrus sinensis','4', 4, 3, 18, 'Buenas', NULL);
CALL InsertTree(472, 'Naranjo', 'Citrus sinensis','4', 4, 3, 18, 'Buenas', NULL);
CALL InsertTree(473, 'Naranjo', 'Citrus sinensis','4', 4, 3, 18, 'Buenas', NULL)
CALL InsertTree(474, 'Naranjo', 'Citrus sinensis','3', 3, 5, 15, 'Buenas', NULL);
CALL InsertTree(475, 'Alamo Mexicano', 'Plantanus mexicana','8', 4, 5, 28, 'Buenas', NULL);
CALL InsertTree(476, 'Palma Washingtonia', 'Washingtonia robusta','13', 4, 12, 45, 'Buenas', NULL);
CALL InsertTree(477, 'Palma', 'Arecaceae','4', 2, 3, 17, 'Buenas', NULL);
CALL InsertTree(478, 'Tepehuaje', 'Lysiloma acapulquense','3.5', 4, 4, 18, 'Buenas', NULL);
CALL InsertTree(479, 'Framboyan', 'Delonix regia','2', 1, 4, 13, 'Buenas', NULL);
CALL InsertTree(480, 'Framboyan', 'Delonix regia','2', 1, 4, 13, 'Buenas', NULL);
CALL InsertTree(481, 'Huizache', 'Vachella farnesiana','9', 7, 6, 32, 'Buenas', NULL);
CALL InsertTree(482, 'Framboyan', 'Delonix regia','1', 0.5, 1, 8, 'Buenas', NULL);
CALL InsertTree(483, 'Naranjo', 'Citrus sinensis','3', 4, 3, 16, 'Buenas', NULL);
CALL InsertTree(484, 'Encino', 'Quercus','5', 4, 5, 22, 'Buenas', NULL);
CALL InsertTree(485, 'Naranjo', 'Citrus sinensis','2', 0.5, 1.5, 10, 'Buenas', 'Quitar');
CALL InsertTree(486, 'Encino', 'Quercus','8', 4, 8, 31, 'Buenas', NULL);
CALL InsertTree(487, 'Encino', 'Quercus','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(488, 'Mora', 'Morus alba','21', 8, 6, 57, 'Buenas', NULL);
CALL InsertTree(489, 'Ebano', 'Ebenopsis ebano','12', 8, 7, 40, 'Buenas', NULL);
CALL InsertTree(490, 'Encino', 'Quercus','8', 6, 4, 28, 'Buenas', NULL);
CALL InsertTree(491, 'Mezquite', 'Prosopis laevigata','7', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(492, 'Potro', 'Equus ferus caballus','5-4', 6, 5, 23, 'Buenas', NULL);
CALL InsertTree(493, 'Potro', 'Equus ferus caballus','7-6-5', 5, 5, 26, 'Buenas', NULL);
CALL InsertTree(494, 'Ebano', 'Ebenopsis ebano','8', 6, 6, 30, 'Buenas', NULL);
CALL InsertTree(495, 'Ebano', 'Ebenopsis ebano','11', 8, 6, 37, 'Buenas', NULL);
CALL InsertTree(496, 'Ebano', 'Ebenopsis ebano','6', 5, 6, 25, 'Buenas', NULL);
CALL InsertTree(497, 'Ebano', 'Ebenopsis ebano','4', 3, 5, 19, 'Buenas', NULL);
CALL InsertTree(498, 'Ebano', 'Ebenopsis ebano','9', 6, 6, 32, 'Buenas', NULL);
CALL InsertTree(499, 'Ebano', 'Ebenopsis ebano','3', 2, 5, 17, 'Buenas', NULL);
CALL InsertTree(500, 'Palma Washingtonia', 'Washingtonia robusta','16', 4, 4, 43, 'Buenas', NULL);
CALL InsertTree(501, 'Tepehuaje', 'Lysiloma acapulquense','11', 6, 6, 36, 'Buenas', '45° de inclinacion');
CALL InsertTree(502, 'Tauce', 'Taxus baccata','16', 10, 7, 49, 'Regulares', NULL);
CALL InsertTree(503, 'Sombrilla Japonesa', 'Koelreuteria paniculata','8', 6, 6, 30, 'Buenas', NULL);
CALL InsertTree(504, 'Tepehuaje', 'Lysiloma acapulquense','8', 6, 8, 32, 'Buenas', '30° de inclinacion');
CALL InsertTree(505, 'Encino', 'Quercus','4', 3, 4, 18, 'Regulares', NULL);
CALL InsertTree(506, 'Naranjo', 'Citrus sinensis','5', 4, 3, 20, 'Buenas', NULL);
CALL InsertTree(507, 'Naranjo', 'Citrus sinensis','5', 4, 2, 19, 'Buenas', NULL);
CALL InsertTree(508, 'Durazno', 'Prunus persica','5', 1, 3, 18, 'Malas', 'Quitar');
CALL InsertTree(509, 'Tepehuaje', 'Lysiloma acapulquense','6-5', 5, 7, 26, 'Buenas', NULL);
CALL InsertTree(510, 'Naranjo', 'Citrus sinensis','2', 2, 2, 12, 'Malas', 'Quitar');
CALL InsertTree(511, 'Naranjo', 'Citrus sinensis','4', 4, 2, 17, 'Malas', 'Quitar Pegados');
CALL InsertTree(512, 'Tepehuaje', 'Lysiloma acapulquense','4', 2, 6, 20, 'Buenas', 'Pegados');
CALL InsertTree(513, 'Encino Roble', 'Quercus','4', 3, 7, 21, 'Buenas', 'Árbol emblematico');
CALL InsertTree(514, 'Tepehuaje', 'Lysiloma acapulquense','6', 3, 7, 25, 'Malas', 'Pegado a barda quitar');
CALL InsertTree(515, 'Encino', 'Quercus','3', 1, 5, 16, 'Buenas', NULL);
CALL InsertTree(516, 'Encino', 'Quercus','2', 1, 4, 13, 'Buenas', NULL);
CALL InsertTree(517, 'Encino', 'Quercus','2.5', 1, 4, 14, 'Buenas', NULL)
CALL InsertTree(518, 'Encino', 'Quercus','2.5', 1, 4, 14, 'Buenas', NULL);
CALL InsertTree(519, 'Ebano', 'Ebenopsis ebano','12', 10, 6, 40, 'Buenas', NULL);
CALL InsertTree(520, 'Huamuchil', 'Pithecellobium dulce','11', 5, 6, 35, 'Malas', NULL);
CALL InsertTree(521, 'Huamuchil', 'Pithecellobium dulce','11', 5, 6, 35, 'Malas', NULL);
CALL InsertTree(522, 'Ebano', 'Ebenopsis ebano','7', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(523, 'Encino', 'Quercus','13', 14, 8, 46, 'Buenas', NULL);
CALL InsertTree(524, 'Palma Washingtonia', 'Washingtonia robusta','11', 4, 5, 34, 'Buenas', NULL);
CALL InsertTree(525, 'Tulia', 'Thuja accidentalis','2', 2, 3, 13, 'Buenas', NULL);
CALL InsertTree(526, 'Encino', 'Quercus','10', 8, 7, 36, 'Buenas', NULL);
CALL InsertTree(527, 'Palma', 'Arecaceae','9', 14, 8, 46, 'Buenas', NULL);
CALL InsertTree(528, 'Palma', 'Arecaceae','9', 14, 8, 46, 'Buenas', NULL);
CALL InsertTree(529, 'Mezquite', 'Prosopis laevigata','9', 8, 7, 34, 'Buenas', NULL);
CALL InsertTree(530, 'Encino', 'Quercus','11', 8, 7, 38, 'Buenas', NULL);
CALL InsertTree(531, 'Anacua', 'Ehretia anacua','9-5-5', 10, 6, 34, 'Buenas', NULL);
CALL InsertTree(532, 'Mezquite', 'Prosopis laevigata','9', 5, 5, 30, 'Buenas', 'Fuste inclinado 45°');
CALL InsertTree(533, 'Mezquite', 'Prosopis laevigata','9', 6, 6, 32, 'Buenas', NULL);
CALL InsertTree(534, 'Mezquite', 'Prosopis laevigata','7', 6, 5, 27, 'Buenas', NULL);
CALL InsertTree(535, 'Mezquite', 'Prosopis laevigata','12', 6, 6, 38, 'Buenas', NULL);
CALL InsertTree(536, 'Encino', 'Quercus','9', 8, 5, 32, 'Buenas', NULL);
CALL InsertTree(537, 'Encino', 'Quercus','9', 8, 5, 32, 'Buenas', NULL);
CALL InsertTree(538, 'Encino', 'Quercus','9', 8, 5, 32, 'Buenas', NULL);
CALL InsertTree(539, 'Encino', 'Quercus','13', 8, 5, 40, 'Buenas', NULL);
CALL InsertTree(540, 'Encino', 'Quercus','8', 8, 5, 30, 'Malas', 'Seco');
CALL InsertTree(541, 'Encino', 'Quercus','11', 8, 5, 36, 'Regulares', NULL);
CALL InsertTree(542, 'Encino', 'Quercus','8', 8, 5, 30, 'Buenas', NULL);
CALL InsertTree(543, 'Encino', 'Quercus','10', 8, 5, 34, 'Buenas', NULL);
CALL InsertTree(544, 'Encino', 'Quercus','11', 8, 5, 36, 'Buenas', NULL);
CALL InsertTree(545, 'Encino', 'Quercus','9', 8, 5, 32, 'Buenas', NULL);
CALL InsertTree(546, 'Encino', 'Quercus','8', 8, 5, 30, 'Buenas', NULL);
CALL InsertTree(547, 'Encino', 'Quercus','10', 8, 5, 34, 'Buenas', NULL);
CALL InsertTree(548, 'Encino', 'Quercus','10', 8, 5, 34, 'Buenas', NULL);
CALL InsertTree(549, 'Encino', 'Quercus','12', 8, 5, 38, 'Buenas', NULL);
CALL InsertTree(550, 'Encino', 'Quercus','9', 8, 5, 32, 'Buenas', NULL);
CALL InsertTree(551, 'Encino', 'Quercus','10', 8, 5, 34, 'Buenas', NULL);
CALL InsertTree(552, 'Encino', 'Quercus','10', 8, 5, 34, 'Buenas', NULL);
CALL InsertTree(553, 'Encino', 'Quercus','5-5-3-3', 6, 6, 24, 'Buenas', NULL);
CALL InsertTree(554, 'Encino', 'Quercus','8', 8, 5, 30, 'Buenas', NULL);
CALL InsertTree(555, 'Encino', 'Quercus','12', 8, 5, 38, 'Buenas', NULL);
CALL InsertTree(556, 'Encino', 'Quercus','9', 8, 5, 32, 'Buenas', NULL);
CALL InsertTree(557, 'Encino', 'Quercus','10', 8, 5, 34, 'Buenas', NULL);
CALL InsertTree(558, 'Ebano', 'Ebenopsis ebano','10', 8, 5, 34, 'Buenas', NULL);
CALL InsertTree(559, 'Mezquite', 'Prosopis laevigata','3', 6, 5, 19, 'Buenas', NULL);
CALL InsertTree(560, 'Encino Roble', 'Quercus','6', 4, 5, 24, 'Buenas', NULL);
CALL InsertTree(561, 'Naranjo', 'Citrus sinensis','3', 3, 3, 15, 'Buenas', NULL);
CALL InsertTree(562, 'Fresno', 'Fraxinus excelsior','30', 7, 6, 74, 'Malas', 'Hueco en base del fuste');
CALL InsertTree(563, 'Pino', 'Pinus sylvestris','10', 4, 12, 39, 'Malas', 'Fuste rajado');
CALL InsertTree(564, 'Encino Roble', 'Quercus','5', 4, 5, 24, 'Buenas', NULL);
CALL InsertTree(565, 'Pino', 'Pinus sylvestris','14', 4, 12, 47, 'Buenas', NULL);
CALL InsertTree(566, 'Tulia', 'Thuja accidentalis','3', 1, 13, 24, 'Buenas', NULL);
CALL InsertTree(567, 'Ebano', 'Ebenopsis ebano','7', 6, 6, 28, 'Buenas', NULL);
CALL InsertTree(568, 'Guayabo', 'Psidium guajava','2', 3, 4, 14, 'Buenas', NULL);
CALL InsertTree(569, 'Encino', 'Quercus','10', 8, 6, 36, 'Buenas', NULL);
CALL InsertTree(570, 'Trueno', 'Ligustrum lucidum','8', 6, 5, 29, 'Regulares', NULL);
CALL InsertTree(571, 'Granado', 'Punica granatum','2', 3, 3, 13, 'Buenas', NULL);
CALL InsertTree(572, 'Naranjo', 'Citrus sinensis','4', 4, 3, 18, 'Buenas', NULL);
CALL InsertTree(573, 'Alamo Sicomoro', 'Ficus sycomorus','3', 3, 5, 18, 'Buenas', NULL);
CALL InsertTree(574, 'Palo Blanco', 'Calycophyllum multiflorum','6', 6, 5, 25, 'Buenas', NULL);
CALL InsertTree(575, 'Encino Roble', 'Quercus','8', 8, 6, 31, 'Buenas', NULL);
CALL InsertTree(576, 'Encino Roble', 'Quercus','10', 8, 6, 35, 'Buenas', NULL);
CALL InsertTree(577, 'Nogal', 'Junglans regia','13', 10, 10, 46, 'Buenas', NULL);
CALL InsertTree(578, 'Nogal', 'Junglans regia','28', 12, 12, 79, 'Buenas', NULL);
CALL InsertTree(579, 'Nogal', 'Junglans regia','5', 5, 4, 21, 'Buenas', NULL);
CALL InsertTree(580, 'Mezquite', 'Prosopis laevigata','8', 8, 7, 32, 'Buenas', NULL);
CALL InsertTree(581, 'Mezquite', 'Prosopis laevigata','4', 4, 5, 20, 'Buenas', NULL);
CALL InsertTree(582, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(583, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(584, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(585, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(586, 'Encino Rojo', 'Quercus rubra','7', 6, 8, 30, 'Buenas', NULL);
CALL InsertTree(587, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(588, 'Encino Rojo', 'Quercus rubra','7', 4, 8, 29, 'Buenas', NULL);
CALL InsertTree(589, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(590, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(591, 'Tulia', 'Thuja accidentalis','9', 4, 5, 30, 'Buenas', NULL);
CALL InsertTree(592, 'Huamuchil', 'Pithecellobium dulce','10-7', 6, 6, 34, 'Malas', 'Pegados');
CALL InsertTree(593, 'Tulia', 'Thuja accidentalis','3', 3, 3, 15, 'Regulares', 'Pegados');
CALL InsertTree(594, 'Tulia', 'Thuja accidentalis','5', 3, 4, 20, 'Regulares', NULL);
CALL InsertTree(595, 'Encino Rojo', 'Quercus rubra','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(596, 'Tulia', 'Thuja accidentalis','5', 4, 3, 20, 'Regulares', NULL);
CALL InsertTree(597, 'Encino', 'Quercus','4', 3, 4, 18, 'Buenas', NULL);
CALL InsertTree(598, 'Encino', 'Quercus','5', 4, 5, 22, 'Buenas', NULL);
CALL InsertTree(599, 'Bugambilia', 'Bougainvillea','2', 4, 2, 13, 'Buenas', NULL);
CALL InsertTree(600, 'Mongolia', 'Tilia mongolica','6', 3, 4, 22, 'Buenas', NULL);
CALL InsertTree(601, 'Guayabo', 'Psidium guajava','2', 2, 5, 15, 'Buenas', NULL);
CALL InsertTree(602, 'Fresno', 'Fraxinus excelsior','15', 12, 7, 48, 'Buenas', NULL);
CALL InsertTree(603, 'Huamuchil', 'Pithecellobium dulce','6', 2, 4, 22, 'Malas', 'Quitar');
CALL InsertTree(604, 'Fresno', 'Fraxinus excelsior','7', 4, 6, 27, 'Buenas', NULL);
CALL InsertTree(605, 'Fresno', 'Fraxinus excelsior','10', 8, 6, 35, 'Buenas', NULL)
CALL InsertTree(606, 'Fresno', 'Fraxinus excelsior','14', 8, 6, 43, 'Buenas', NULL);
CALL InsertTree(607, 'Fresno', 'Fraxinus excelsior','10', 8, 6, 35, 'Buenas', NULL);
CALL InsertTree(608, 'Fresno', 'Fraxinus excelsior','12', 8, 7, 40, 'Buenas', NULL);
CALL InsertTree(609, 'Fresno', 'Fraxinus excelsior','13', 8, 7, 42, 'Buenas', NULL);
CALL InsertTree(610, 'Fresno', 'Fraxinus excelsior','15', 8, 6, 45, 'Buenas', NULL);
CALL InsertTree(611, 'Fresno', 'Fraxinus excelsior','13', 8, 6, 41, 'Buenas', NULL);
CALL InsertTree(612, 'Fresno', 'Fraxinus excelsior','12', 8, 6, 39, 'Buenas', NULL);
CALL InsertTree(613, 'Fresno', 'Fraxinus excelsior','14', 10, 8, 46, 'Buenas', NULL);
CALL InsertTree(614, 'Fresno', 'Fraxinus excelsior','18', 10, 8, 54, 'Buenas', NULL);
CALL InsertTree(615, 'Fresno', 'Fraxinus excelsior','23', 10, 8, 64, 'Buenas', NULL);
CALL InsertTree(616, 'Limon', 'Citrus limon','6', 4, 4, 23, 'Buenas', NULL);
CALL InsertTree(617, 'Encino Roble', 'Quercus','12', 8, 6, 39, 'Buenas', NULL);
CALL InsertTree(618, 'Encino Roble', 'Quercus','12', 8, 6, 39, 'Buenas', NULL);
CALL InsertTree(619, 'Palo Blanco', 'Calycophyllum multiflorum','4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(620, 'Ebano', 'Ebenopsis ebano','3', 2, 3, 15, 'Buenas', NULL);
CALL InsertTree(621, 'Huizache', 'Vachella farnesiana','10', 10, 5, 35, 'Buenas', NULL);
CALL InsertTree(622, 'Pino Pincel', 'Coris monspeliensis','6', 1, 6, 23, 'Buenas', NULL);
CALL InsertTree(623, 'Palma', 'Arecaceae','9', 6, 7, 33, 'Buenas', NULL);
CALL InsertTree(624, 'Palma', 'Arecaceae','9', 6, 7, 33, 'Buenas', NULL);
CALL InsertTree(625, 'Palma', 'Arecaceae','4', 2, 2, 16, 'Buenas', NULL);
CALL InsertTree(626, 'Palma', 'Arecaceae','9', 6, 7, 33, 'Buenas', NULL);
CALL InsertTree(627, 'Palo Blanco', 'Calycophyllum multiflorum','7-7-5-5', 10, 6, 30, 'Buenas', NULL);
CALL InsertTree(628, 'Palo Blanco', 'Calycophyllum multiflorum','7-5', 8, 5, 28, 'Buenas', NULL);
CALL InsertTree(629, 'Pino Pincel', 'Coris monsepeliensis','6', 2, 7, 25, 'Buenas', NULL);
CALL InsertTree(630, 'Palo Blanco', 'Calycophyllum multiflorum','3', 3, 5, 17, 'Buenas', NULL);
CALL InsertTree(631, 'Palo Blanco', 'Calycophyllum multiflorum','5-4', 6, 5, 23, 'Buenas', NULL);
CALL InsertTree(632, 'Encino', 'Quercus','9', 10, 5, 33, 'Buenas', NULL);
CALL InsertTree(633, 'Encino', 'Quercus','11', 10, 6, 38, 'Buenas', NULL);
CALL InsertTree(634, 'Encino', 'Quercus','12', 8, 6, 39, 'Buenas', NULL);
CALL InsertTree(635, 'Encino Roble', 'Quercus','18', 8, 6, 51, 'Buenas', NULL);
CALL InsertTree(636, 'Encino Roble', 'Quercus','14', 8, 6, 43, 'Buenas', NULL);
CALL InsertTree(637, 'Encino Roble', 'Quercus','16', 8, 6, 47, 'Buenas', NULL);
CALL InsertTree(638, 'Encino Roble', 'Quercus','9', 8, 5, 32, 'Buenas', NULL);
CALL InsertTree(639, 'Encino', 'Quercus','6', 8, 6, 27, 'Buenas', NULL);
CALL InsertTree(640, 'Encino Roble', 'Quercus','8', 8, 6, 31, 'Buenas', NULL);
CALL InsertTree(641, 'Encino Roble', 'Quercus','5', 5, 4, 21, 'Buenas', NULL);
CALL InsertTree(642, 'Anacua', 'Ehretia anacua','4', 6, 4, 20, 'Buenas', NULL);
CALL InsertTree(643, 'Encino Roble', 'Quercus','5', 6, 5, 23, 'Buenas', NULL);
CALL InsertTree(644, 'Anacua', 'Ehretia anacua','33', 12, 6, 83, 'Buenas', NULL);
CALL InsertTree(645, 'Encino Roble', 'Quercus','20', 10, 6, 56, 'Buenas', NULL);
CALL InsertTree(646, 'Nispero', 'Eriobotrya japonica','8', 6, 5, 29, 'Buenas', NULL);
CALL InsertTree(647, 'Pino Pincel', 'Coris monsepeliensis','6', 1, 8, 25, 'Buenas', NULL);
CALL InsertTree(648, 'Pino Pincel', 'Coris monsepeliensis','6', 1, 8, 25, 'Buenas', NULL);
CALL InsertTree(649, 'Huamuchil', 'Pithecellobium dulce','13-10-8', 8, 7, 42, 'Malas', NULL);
CALL InsertTree(650, 'Nogal', 'Junglans regia','1.5', 1, 2, 10, 'Buenas', NULL);
CALL InsertTree(651, 'Encino', 'Quercus','5', 10, 4, 20, 'Buenas', NULL);
CALL InsertTree(652, 'Potro', 'Equus ferus caballus','4-3-3-4', 4, 4, 19, 'Buenas', NULL);
CALL InsertTree(653, 'Ebano', 'Ebenopsis ebano','11', 6, 7, 37, 'Buenas', NULL);
CALL InsertTree(654, 'Ebano', 'Ebenopsis ebano','8', 7, 6, 30, 'Buenas', NULL);
CALL InsertTree(655, 'Encino', 'Quercus','5', 4, 4, 21, 'Buenas', NULL);
CALL InsertTree(656, 'Mezquite', 'Prosopis laevigata','6', 7, 4, 24, 'Buenas', NULL);
CALL InsertTree(657, 'Mezquite', 'Prosopis laevigata','7', 7, 4, 26, 'Buenas', NULL);
CALL InsertTree(658, 'Huamuchil', 'Pithecellobium dulce','20', 6, 5, 53, 'Malas', NULL);
CALL InsertTree(659, 'Huamuchil', 'Pithecellobium dulce','20', 6, 5, 53, 'Malas', NULL);
CALL InsertTree(660, 'Fresno', 'Fraxinus excelsior','14-11', 6, 6, 42, 'Malas', 'Mala ubicacion');
CALL InsertTree(661, 'Encino', 'Quercus','3', 2, 3, 15, 'Buenas', NULL);
CALL InsertTree(662, 'Huamuchil', 'Pithecellobium dulce','4', 3, 5, 19, 'Buenas', 'Mala ubicacion');
CALL InsertTree(663, 'Tepehuaje', 'Lysiloma acapulquense','4', 4, 6, 21, 'Buenas', 'Mala ubicacion');
CALL InsertTree(664, 'Tepehuaje', 'Lysiloma acapulquense','3', 2, 3, 15, 'Malas', 'Pegado a barda quitar');
CALL InsertTree(665, 'Palo Blanco', 'Calycophyllum multiflorum','7-7-9-7', 7, 9, 31, 'Buenas', NULL);
CALL InsertTree(666, 'Fresno', 'Fraxinus excelsior','14', 10, 7, 45, 'Buenas', NULL);
CALL InsertTree(667, 'Fresno', 'Fraxinus excelsior','14', 10, 7, 45, 'Buenas', NULL);
CALL InsertTree(668, 'Huizache', 'Vachella farnesiana','5', 6, 4, 22, 'Buenas', NULL);
CALL InsertTree(669, 'Tepehuaje', 'Lysiloma acapulquense','8', 7, 6, 30, 'Buenas', NULL);
CALL InsertTree(670, 'Ebano', 'Ebenopsis ebano','3', 1, 3, 14, 'Buenas', NULL);
CALL InsertTree(671, 'Palo Blanco', 'Calycophyllum multiflorum','4', 4, 3, 18, 'Buenas', NULL);

SELECT * FROM TreeInfo;
